/* DO NOT EDIT THIS FILE - it is machine generated */
#include <android/log.h>
#include <jni.h>
#include <stddef.h>
#include "log.h"
/* Header for class com_hezb_live_recorder_rtmp_RtmpClient */

#ifndef _Included_com_hezb_live_recorder_rtmp_RtmpClient
#define _Included_com_hezb_live_recorder_rtmp_RtmpClient
#ifdef __cplusplus
extern "C" {
#endif

 JNIEXPORT jlong JNICALL Java_com_hezb_live_recorder_rtmp_RtmpClient_open
 (JNIEnv * env, jobject thiz, jstring url_, jboolean isPublishMode);

 JNIEXPORT jint JNICALL Java_com_hezb_live_recorder_rtmp_RtmpClient_read
 (JNIEnv * env, jobject thiz, jlong rtmp, jbyteArray data_, jint offset, jint size);

 JNIEXPORT jint JNICALL Java_com_hezb_live_recorder_rtmp_RtmpClient_write
 (JNIEnv * env, jobject thiz, jlong rtmp, jbyteArray data, jint size, jint type, jint ts);

 JNIEXPORT jint JNICALL Java_com_hezb_live_recorder_rtmp_RtmpClient_close
 (JNIEnv * env, jobject thiz, jlong rtmp);


#ifdef __cplusplus
}
#endif
#endif
